config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "auctions#index"

  get '/auctions/my_bids', to: 'auctions#my_bids', as: :my_bids
  get '/auctions/my_auctions', to: 'auctions#my_auctions', as: :my_auctions

  resources :auctions do
    resources :bids
    put :publish
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection

  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    cannot :manage, Bid do |bid|
      bid.user == user
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities


  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  include AASM

  belongs_to :user
  has_many :bids, dependent: :destroy

aasm do
  state :draft, initial: true
  state :published
  state :reserve_met
  state :won
  state :cancelled
  state :reserve_not_met

  event :publish do
   transitions from: :draft, to: :published
 end

 event :reserve_met do
   transitions from: :reserve_not_met, to: :reserve_met
   transitions from: :draft, to: :reserve_met
   transitions from: :published, to: :reserve_met
   transitions from: :reserve_met, to: :reserve_met
 end

 event :won do
   transitions from: :published, to: :won
 end

 event :cancelled do
   transitions from: :published, to: :cancelled
   transitions from: :reserve__not_met, to: :cancelled
   transitions from: :reserve_met, to: :cancelled
 end

 event :reserve_not_met do
   transitions from: :draft, to: :reserve_not_met
   transitions from: :published, to: :reserve_not_met
 end

end

end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :auction

  validate :higher_bid

  def higher_bid
    other_bids = self.auction.bids
    unless(self.bid_amount > other_bids.maximum("bid_amount").to_f)
      self.errors.add(:higher_bid, "must be higher than maximum")
    end
  end

# class MyValidator < ActiveModel::Validator
#   def higher_bid(bid)
#     unless bid.bid_amount > bid.maximum("bid_amount")
#       bid.errors[:bid_amount]
#     end
#   end
#
# end

  # validate :bid_amount
  #
  # def higher_bid
  #   bid.bid_amount > bid.maximum("bid_amount")
  # end

# max_bid_amount = Bid.where(:id => item.id).maximum(:bid_amount)
#
# if @bid.bid_amount > max_bid_amount
#   # proceed with bid placement
# else
#   # do something, return some flag, nil or whatever
# end
#
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

    validates :email, presence: true, uniqueness: true,
              format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

    has_many :auctions, dependent: :destroy

    has_many :bids, dependent: :destroy

    def full_name
      "#{first_name} #{last_name}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  require 'aasm'

    def authenticate_user!
     redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
   end

   def user_signed_in?
     current_user.present?
   end
   helper_method :user_signed_in?

   def current_user
     @current_user ||= User.find_by_id session[:user_id]
   end

   helper_method :current_user

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @auctions = Auction.order(created_at: :desc)
  end

  def new
    @auction = Auction.new
  end

  def create

    auctions_params = params.require(:auction).permit([:title, :details, :ends_on, :reserve_price])
    @auction = Auction.create auctions_params

    if @auction.save
  # render :show
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def edit
  end

  def show
    @auction = Auction.find params[:id]
    @bid = Bid.new
    # @last_bid = Bid.last
    # @highest_bid = @auction.bids.last
    @highest_bid = @auction.bids.maximum("bid_amount")
    # if @auction.published? == false
  end

  def my_bids
    # @user = User.bids.order(created_at: :desc)
    @bids = current_user.bids.order(created_at: :desc)
  end

  def my_auctions
    # @user = User.bids.order(created_at: :desc)
    @auctions = Auction.order(created_at: :desc)
  end

  def update
    @auction = Auction.find params[:id]
    @auction.publish!
    redirect_to auction_path(@auction)
  end

  # def update
  #   service = Auctions::UpdateAuction.new
  #   if service.call
  #     redirect_to auction_path(service.auction), notice: "Auction published!"
  #   else
  #     @auction = service.auction
  #     render :new
  #   end
  # end

def destroy
  @auction = Auction.find params[:id]
  @auction.cancelled!
  redirect_to auction_path(@auction)
end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def create
    @auction          = Auction.find params[:auction_id]
    bid_params = params.require(:bid).permit(:bid_amount)
    @bid       = Bid.new bid_params
    @bid.auction  = @auction
    @bid.user = current_user
    if @bid.save
      redirect_to auction_path(@auction), notice: "Bid created"
    else
      render "/auctions/show"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in"
    else
      flash[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
   session[:user_id] = nil
   redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                              :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/all_bids.html.erb
sdfsd
<h1>All My Bids</h1>

<br>

<% @bids.each do |bid| %>

 <%= bid.auction.title %>:
$<%= bid.bid_amount %>

<%#= bid.user.full_name %>
<br>
<br>

<% end %>

app/views/auctions/index.html.erb
<h1>Published Auctions</h1>

<% @auctions.each do |auction| %>
  <% if auction.draft? != true && auction.cancelled? != true %>
    <%= link_to auction.title, auction_path(auction) %>
    <hr>
  <% end %>
<% end %>

app/views/auctions/my_auctions.html.erb
<h1>Unpublished Auctions</h1>

<% @auctions.each do |auction| %>
  <% if auction.draft? == true || auction.cancelled? == true %>
    <%= link_to auction.title, auction_path(auction) %>
    <hr>
  <% end %>
<% end %>

app/views/auctions/my_bids.html.erb
sdfsd
<h1>My Bids</h1>

<% @bids.each do |bid| %>

 <%= bid.auction.title %>:
$<%= bid.bid_amount %>

<%#= bid.user.full_name %>
<hr>

<% end %>

app/views/auctions/new.html.erb
<%= @auction.errors.full_messages.join(", ") %>
<%= form_for @auction do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_area :details %>
  </div>
  <div>
    <%= f.label :ends_on %>
    <%= f.date_field :ends_on %>
  </div>
  <div>
    <%= f.label :reserve_price %>
    <%= f.number_field :reserve_price %>
  </div>

  <%= f.submit %>

<% end %>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>

<p><%= @auction.details %></p>

<p>Ends on: <%= @auction.ends_on %></p>

<p>Current price: $<%= @highest_bid %></p>
<p>Reserve price: $<%= @auction.reserve_price %></p>

<%#= button_to "Publish", action: @auction.publish%>

<% if @auction.draft? == true %>
<%= form_for(@auction, method: :put, data: { confirm: "Are you sure you want to publish?" }) do |f| %>
  <%= f.submit "Publish", :controller => :auctions, :action => :publish %>
<% end %>
<% end %>

<% if @auction.draft? != true && @auction.cancelled? != true %>
<%= form_for(@auction, method: :delete, data: { confirm: "Are you sure you want to cancel?" }) do |f| %>
  <%= f.submit "Cancel", :controller => :auctions, :action => :cancel %>
<% end %>
<% end %>


<p>Auction State: <%= @auction.aasm_state %></p>

<% if @highest_bid.to_f >= @auction.reserve_price %>
  <p>Reserve Price Met</p>
<% else %>
  <p>Reserve Price Not Met</p>
<% end %>

<%#if can? :view, @bid %>
<%# if can? :create, @bid%>

<%# if @auction.user != current_user %>

<% if @auction.draft? != true %>

<%= @bid.errors.full_messages.join(", ") %>
<%= form_for [@auction, @bid] do |f| %>
<div>
  <%= f.label :bid_amount %>
  <%= f.number_field :bid_amount %>
</div>

<%= f.submit %>
<% end %>

<%# if can? :create, @bid %>
<h4>Previous Bids</h4>

  <% @auction.bids.reverse_each do |bid| %>
    <p>$<%= bid.bid_amount %> at <%= bid.created_at %> by <%= bid.user.full_name %></p>
    <hr>
    <% if @highest_bid.to_f >= @auction.reserve_price && @auction.cancelled? != true  %>
      <% @auction.reserve_met! == true %>
    <% end %>
  <% end %>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biddr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="wrapper">

    <%= link_to "Published Auctions", auctions_path %>
    <%= link_to "Unpublished Auctions", my_auctions_path %>

    <%= link_to "New Auction", new_auction_path %>

      <%= link_to "My Bids", my_bids_path %>


    <% if user_signed_in? %>
      Welcome <%= current_user.first_name  %>,
      <%= link_to "Logout", sessions_path, method: :delete,
          data: {confirm: "are you sure you want to log out?"}%>
    <% else %>
      <%= link_to "Login", new_session_path %> |
      <%= link_to "Sign Up", new_user_path %>
    <% end %>

<hr>

    <%= yield %>

  </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>